//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebsiteBanHangEntities : DbContext
    {
        public WebsiteBanHangEntities()
            : base("name=WebsiteBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand_2119110245> Brand_2119110245 { get; set; }
        public virtual DbSet<Category_2119110245> Category_2119110245 { get; set; }
        public virtual DbSet<Order_2119110245> Order_2119110245 { get; set; }
        public virtual DbSet<OrderDetail_2119110245> OrderDetail_2119110245 { get; set; }
        public virtual DbSet<Product_2119110245> Product_2119110245 { get; set; }
        public virtual DbSet<Slider_2119110245> Slider_2119110245 { get; set; }
        public virtual DbSet<User_2119110245> User_2119110245 { get; set; }
        public virtual DbSet<Post_2119110245> Post_2119110245 { get; set; }
    }
}
