//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_2119110245
    {
        public int PostId { get; set; }
        public string PostTitle { get; set; }
        public string PostSlug { get; set; }
        public string PostAvatar { get; set; }
        public string PostDetail { get; set; }
        public Nullable<System.DateTime> PostDateCreate { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<int> status { get; set; }
    }
}
